name: Kiểm tra

on:
  push:
    paths:
      - 'top/bestPlayers.html'
      - 'top/tvlt.html'
      - 'top/dttv.html'
      - 'top/cbtt.thml'
      - 'leaderboard/cbtt.html'
      - 'leaderboard/tvlt.html'
      - 'leaderboard/dttv.html'
      - 'index.html'
  pull_request:
    paths:
      - 'index.html'
      - 'top/bestPlayers.html'
      - 'top/tvlt.html'
      - 'top/dttv.html'
      - 'top/cbtt.thml'
      - 'leaderboard/cbtt.html'
      - 'leaderboard/tvlt.html'
      - 'leaderboard/dttv.html'
  

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: test-pages
      url: ${{ steps.html_preview.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'index.html'
  
