name: Kiểm tra

on: [push, pull_request]

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: test-pages
      url: ${{ steps.html_preview.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'index.html'
  
