name: Cập nhật tệp .md sang tệp .html

on:
  push:
    branches: [ main ]
    paths:
      - 'top/bestPlayers.md'
      - 'top/tvlt.md'
      - 'top/dttv.md'
      - 'top/cbtt.md'
      - 'leaderboard/cbtt.md'
      - 'leaderboard/tvlt.md'
      - 'leaderboard/dttv.md'

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: Thiết lập Python '3.12'
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Cài đặt dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Cập nhật Bảng xếp hạng
        run: |
          python3 md2html.py
      - name: Cam kết & Đẩy tệp
        run: |
          git config --local user.email "vietdinh856@gmail.com"
          git config --local user.name "TVLT-Admim"
          git add -A
          git commit -m "Cập nhật BXH từ tệp md sang tệp html"
          git push --force
